# Generated by Django 4.0.3 on 2022-07-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0003_rename_gov_entites_alert_gov_entities_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
