# Generated by Django 4.0.3 on 2022-07-20 00:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0004_alert_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alert",
            name="email",
        ),
    ]
