# Generated by Django 4.0.3 on 2022-11-03 23:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0005_remove_alert_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alert",
            name="territory_id",
        ),
        migrations.AddField(
            model_name="alert",
            name="territories",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=7),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
