name: Lint and unit checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  # Skip por hora porque está quebrando...
  # lint:
  #   name: Python lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.9'
  #         cache: 'pip'
  #         cache-dependency-path: |
  #           requirements-dev.txt
  #     - name: Install dev dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r requirements-dev.txt
  #     - name: Run flake8
  #       run: |
  #         flake8 app cli libs querido_diario reports
  #     - name: Run isort check
  #       run: |
  #         isort --check-only --diff .
  #     - name: Run black check
  #       run: |
  #         black --check .

  unit:
    name: Unit tests (docker compose)
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Verify Docker Compose
        run: docker compose version
      - name: Run tests
        env:
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1
        run: |
          docker compose -f docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from backend
      - name: Cleanup
        if: always()
        run: docker compose -f docker-compose.test.yml down -v || true
