name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run tests
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-latest
          - platform: linux/arm64
            runner: ubuntu-24.04-arm64
    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Verify Docker Compose
        run: |
          docker compose version
      - name: Build and test for platform
        env:
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1
        run: |
          # Update docker-compose.test.yml to build for specific platform
          sed -i "/dockerfile: Dockerfile/a\\      platforms:\\n        - ${{ matrix.platform }}" docker-compose.test.yml

          # Run full test suite on native architecture
          docker compose -f docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from backend
      - name: Cleanup
        if: always()
        run: |
          docker compose -f docker-compose.test.yml down -v || true
